/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class luo_uvc_jni_ImageProc */

#include "common.h"

#ifndef _Included_luo_uvc_jni_ImageProc
#define _Included_luo_uvc_jni_ImageProc

#pragma message("------------------------ __cplusplus 1")

#ifdef __cplusplus
extern "C" {
#pragma message("------------------------ __cplusplus 2")
#endif

/*
 * Class:     luo_uvc_jni_ImageProc
 * Method:    grayProc
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_luo_uvc_jni_ImageProc_grayProc
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     luo_uvc_jni_ImageProc
 * Method:    connectCamera
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_luo_uvc_jni_ImageProc_connectCamera
  (JNIEnv *, jclass, jint);

/*
 * Class:     luo_uvc_jni_ImageProc
 * Method:    getFrame
 * Signature: ()Lluo/uvc/jni/ImageProc/FrameInfo;
 */
JNIEXPORT jobject JNICALL Java_luo_uvc_jni_ImageProc_getFrame
  (JNIEnv *, jclass);

/*
 * Class:     luo_uvc_jni_ImageProc
 * Method:    releaseCamera
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_luo_uvc_jni_ImageProc_releaseCamera
  (JNIEnv *, jclass);

/*
 * Class:     luo_uvc_jni_ImageProc
 * Method:    startRecord
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_luo_uvc_jni_ImageProc_startRecord
  (JNIEnv *, jclass, jstring);

/*
 * Class:     luo_uvc_jni_ImageProc
 * Method:    stopRecord
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_luo_uvc_jni_ImageProc_stopRecord
  (JNIEnv *, jclass);

/*
 * Class:     luo_uvc_jni_ImageProc
 * Method:    getWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_luo_uvc_jni_ImageProc_getWidth
  (JNIEnv *, jclass);

/*
 * Class:     luo_uvc_jni_ImageProc
 * Method:    getHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_luo_uvc_jni_ImageProc_getHeight
  (JNIEnv *, jclass);


char* jstringToChar(JNIEnv* env, jstring jstr);

#ifdef __cplusplus
}
#endif

#endif
